### PR TITLE
upgrade to iced 0.9 + replace radio with pick_list

### PR DESCRIPTION
**Pull request by BKSalman**
somewhat addresses #15

### CODE REVIEW

**Comment by BKSalman** [comment]
@eclairevoyant could you review the changes? I replaced radio with a drop-down menu

**Comment by eclairevoyant** [comment]
Dropdown seems fine, though the gui itself is cut off:

image

It might be reporting a smaller size than it is intended to be; trimmed output from `swaymsg -t get_tree` below:

```
              "geometry": {
                "x": 0,
                "y": 0,
                "width": 738,
                "height": 561
              },
              "name": "ytdlp-gui",
```

**Comment by BKSalman** [comment]
> though the gui itself is cut off

yes, it's kinda oversized on my machine, maybe related to scaling or something, will resolve that, and commit it

**Comment by BKSalman** [comment]
how about now? it looks fine on my machine now, hopefully on your machine too @eclairevoyant

**Comment by BKSalman** [comment]
ye I think this is fine, if it looks broken, people can report it to me

**Pull request merged**
